all:
	@make -f ./make_analysis
	@make -f ./make_step_through_events 
clean:
	@make -f ./make_analysis clean
	@make -f ./make_step_through_events clean

clobber:	
	@make -f ./make_analysis clobber
	@make -f ./make_step_through_events clobber

